name: Test if build is working

on:
  pull_request:
      types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          token: ${{ secrets.JELLYROCK_BOT_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install NPM dependencies
        run: npm ci
      - name: Checkout jellyrock
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          repository: cewert/jellyrock
          path: jellyrock
          ref: main
      - name: Build code docs
        # TODO: fix jsdoc build errors then remove '|| true' from run command below
        run: npm run build || true
