name: Test if build is working

on:
  pull_request:
      types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          token: ${{ secrets.JELLYROCK_BOT_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install NPM dependencies
        run: npm ci
      - name: Checkout jellyrock
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: cewert/jellyrock
          path: jellyrock
          ref: main
      - name: Build code docs
        # TODO: fix jsdoc build errors then remove '|| true' from run command below
        run: npm run build || true
