name: Update code docs

on:
  repository_dispatch:
    types: [code-update]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ github.ref_name }}
          token: ${{ secrets.JELLYROCK_BOT_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: Install NPM dependencies
        run: npm ci
      - name: Checkout jellyrock
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: cewert/jellyrock
          path: jellyrock
          ref: main
      - name: Build code docs
        # TODO: fix jsdoc build errors then remove '|| true' from run command below
        run: npm run build || true
      - name: Commit any changes
        uses: stefanzweifel/git-auto-commit-action@28e16e81777b558cc906c8750092100bbb34c5e3 # v7
        with:
          commit_message: Update code docs
          # use JellyRock-bot to commit the changes instead of the default github-actions[bot]
          commit_user_name: JellyRock-bot
          commit_user_email: c.ewert@gmail.com
          # use JellyRock-bot to author the changes instead of the default author of the merge commit
          commit_author: JellyRock-bot <c.ewert@gmail.com>
